### ISSUE TITLE
Google Drive is messed up and Google Docs, Slides, etc. don't work.

### ISSUE THREAD

**Issue by DatGamerYoloYT** [toiletflusher/google2009#3]
When I use the extension that I use for the User Agent, Google Drive gets messed up and turns into what I believe is the mobile version. I tried making it so that only google.com has the different User Agent but Google Drive is STILL messed up. It's probably because Google Drive's url is a sub-domain (drive.google.com) so the sub-domain gets ignored and the main domain is checked and because the main domain is google.com, it uses the different User Agent. Also, Google Docs, Slides and some of the other services in Google Workspace don't seem to work. They just get stuck at a screen that looks like this:
![image](https://user-images.githubusercontent.com/84749503/209453341-ee5370d4-ea93-4b08-b25c-0ca83dd2470a.png)
Is there a way to fix this?

**Comment by comdlg32** [comment]
Fixed. The homepage style should now only apply on these URLs:
URL: https://www.google.com/
URLs that begin with: https://www.google.com/?
URLs that begin with: https://www.google.com/preferences
URLs that begin with: https://www.google.com/webhp
URLs that begin with: https://www.google.com/imghp
